// Mapeamento completo das 29 disciplinas CS
export const DISCIPLINAS = [
  { nome: 'Direito Constitucional', slug: 'constitucional', icone: '⚖️', cor: '#3B82F6' },
  { nome: 'Direito Penal Geral', slug: 'penal-geral', icone: '🔒', cor: '#EF4444' },
  { nome: 'Direito Penal Especial', slug: 'penal-especial', icone: '🔐', cor: '#DC2626' },
  { nome: 'Direito Civil', slug: 'civil', icone: '📜', cor: '#8B5CF6' },
  { nome: 'Processo Civil', slug: 'processo-civil', icone: '📋', cor: '#7C3AED' },
  { nome: 'Processo Penal', slug: 'processo-penal', icone: '🏛️', cor: '#B91C1C' },
  { nome: 'Direito Administrativo', slug: 'administrativo', icone: '🏢', cor: '#F59E0B' },
  { nome: 'Direito Tributário', slug: 'tributario', icone: '💰', cor: '#10B981' },
  { nome: 'Direito do Trabalho', slug: 'trabalho', icone: '👷', cor: '#F97316' },
  { nome: 'Processo do Trabalho', slug: 'processo-trabalho', icone: '⚙️', cor: '#EA580C' },
  { nome: 'Direito Empresarial', slug: 'empresarial', icone: '🏦', cor: '#6366F1' },
  { nome: 'Direito Ambiental', slug: 'ambiental', icone: '🌿', cor: '#22C55E' },
  { nome: 'Direitos Humanos', slug: 'humanos', icone: '✊', cor: '#EC4899' },
  { nome: 'Criminologia', slug: 'criminologia', icone: '🔍', cor: '#64748B' },
  { nome: 'Direito Agrário', slug: 'agrario', icone: '🌾', cor: '#84CC16' },
  { nome: 'Direito Eleitoral', slug: 'eleitoral', icone: '🗳️', cor: '#0EA5E9' },
  { nome: 'Direito Econômico', slug: 'economico', icone: '📊', cor: '#14B8A6' },
  { nome: 'Direito Urbanístico', slug: 'urbanistico', icone: '🏙️', cor: '#A855F7' },
  { nome: 'ECA', slug: 'eca', icone: '👶', cor: '#F472B6' },
  { nome: 'Direito do Consumidor', slug: 'consumidor', icone: '🛒', cor: '#FB923C' },
  { nome: 'Direito Financeiro', slug: 'financeiro', icone: '💵', cor: '#34D399' },
  { nome: 'Direito Internacional Público', slug: 'internacional', icone: '🌍', cor: '#06B6D4' },
  { nome: 'Execuções Penais', slug: 'execucoes-penais', icone: '⛓️', cor: '#78716C' },
  { nome: 'Difusos e Coletivos', slug: 'difusos-coletivos', icone: '👥', cor: '#D946EF' },
  { nome: 'Fazenda Pública em Juízo', slug: 'fazenda-publica', icone: '🏛️', cor: '#0284C7' },
  { nome: 'Penal e Proc. Penal Militar', slug: 'penal-militar', icone: '🎖️', cor: '#4B5563' },
  { nome: 'Humanística', slug: 'humanistica', icone: '📖', cor: '#E11D48' },
  { nome: 'Previdenciário', slug: 'previdenciario', icone: '🏥', cor: '#0D9488' },
  { nome: 'Princípios e Atribuições do MP', slug: 'mp-atribuicoes', icone: '⚔️', cor: '#7C2D12' },
];
